require: rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable 
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'app/jobs/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/spring.rb'
    - 'config/puma.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'spec/features/*'
    - 'test/*'
    - 'test/channels/application_cable/connection_test.rb'
    - 'Rakefile'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/factories/self_tests.rb'
    - 'spec/factories/*'


Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true

Layout/LineLength:
  Max: 80
  Enabled: true

Style/AsciiComments:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
  
Lint/RaiseException:
  Enabled: true
  
Lint/StructNewOverride:
  Enabled: true
  
Style/ExponentialNotation:
  Enabled: true
  
Style/HashEachMethods:
  Enabled: true
  
Style/HashTransformKeys:
  Enabled: true
  
Style/HashTransformValues:
  Enabled: true